dist: bionic
language: c
cache:
  - pip
  - ccache

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install libevent -y
  - sudo apt-get install python3 -y
  - sudo apt-get install python3-pip -y
  - sudo apt-get install python3-setuptools -y
  - sudo apt-get install python3-dev -y
  - pip3 install --upgrade --user travis pip setuptools wheel virtualenv

install: "pip3 install --user -r rpctest/requirements.txt"

before_script:
  - ./travis-build.sh

script:
  - make
  - ./nspv ILN
  - cd rpctest
  - python3 -m pytest test_nspv.py
