language: c
python:
  - "3.7"
cache:
  - pip
  - ccache

compiler:
  - gcc

install: "pip3 install --user -r rpctest/requirements.txt"

before_script:
  - ./travis-build.sh

script:
  - make
  - ./nspv ILN
  - cd rpctest
  - python3 -m pytest test_nspv.py
