dist: bionic
language: c
cache:
  - pip
  - ccache

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install python3

install: "pip3 install --user -r rpctest/requirements.txt"

before_script:
  - ./travis-build.sh

script:
  - make
  - ./nspv ILN
  - cd rpctest
  - python3 -m pytest test_nspv.py
