name: LibNspvCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Env_setup
      env: 
        DEBIAN_FRONTEND: noninteractive
    - name: Deps
      run: apt-get install -q libsodium-dev curl libevent-dev git cmake nano wget ntp ntpdate automake unzip autoconf libtool -y
    - name: Build
      run: ./onetime
