name: LibNspvCI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, macOS-10.14]

    steps:
    - uses: actions/checkout@v1

    - name: Build (Linux)
      env:
        DEBIAN_FRONTEND: noninteractive
      if: runner.os == 'Linux'
      run: | 
        sudo apt-get install -q libsodium-dev curl libevent-dev cmake nano wget ntp ntpdate automake unzip autoconf libtool python3-dev python3-setuptools libcurl4-openssl-dev libssl-dev -y
        ./onetime

    - name: Build (MacOS)
      if: runner.os == 'macOS'
      run: | 
        brew install libsodium libevent automake autoconf libtool
        brew install curl
        python3 -m pip install --upgrade setuptools
        python3 -m pip install --upgrade pip
        ./onetime

    - name: Tests
      env:
        WALL: ${{ secrets.LIN_WALL }}
        ADDRESS: ${{ secrets.LIN_ADDRESS }}
        CHAIN: ${{ secrets.LIN_CHAIN }}
      run: |
        /usr/bin/pip3 install -r ./rpctest/requirements.txt
        /usr/bin/python3 ./rpctest/actions.py
